CREATE DATABASE WishList_Senai

CREATE TABLE ListaDesejos(
idDesejo TINYINT PRIMARY KEY IDENTITY,
Titulo VARCHAR(30),
Descricao VARCHAR(250),
DataCriacao DATETIME
)

CREATE TABLE Usuarios(
idUsuario SMALLINT PRIMARY KEY IDENTITY,
Nome VARCHAR(100),
Email VARCHAR(256),
Senha VARCHAR(16)
)
